### ISSUE TITLE
some ideas of mine

### ISSUE THREAD

**Issue by gordonwalkedby** [UltraTechX/Crowbar-Command-Line#1]
- creative commons license is not very suit for a program. https://choosealicense.com/non-software/
- why not add a .gitignore file like [this one](https://github.com/gordonwalkedby/WLib2/blob/master/.gitignore).
- anyway, your work is great! now i can write my own script with it.

**Comment by UltraTechX** [comment]
> * creative commons license is not very suit for a program. https://choosealicense.com/non-software/
> * why not add a .gitignore file like [this one](https://github.com/gordonwalkedby/WLib2/blob/master/.gitignore).
> * anyway, your work is great! now i can write my own script with it.

Thanks for your feedback! I am glad to see people other than myself have a use for it!

I would like to point out that the license can't be changed from creative commons as I am required to use the same license as the original Crowbar program used, as ShareAlike is a part of the creative commons license.
> ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original

I didn't think to look/add a .gitignore at the time of making this program, so I will go ahead and add that now. Might lessen the repository size a bit.

Anyways, thanks for your input. Have a nice evening! Feel free to respond with any more suggestions/questions!

**Comment by gordonwalkedby** [comment]
> 
> 
> > * creative commons license is not very suit for a program. https://choosealicense.com/non-software/
> > * why not add a .gitignore file like [this one](https://github.com/gordonwalkedby/WLib2/blob/master/.gitignore).
> > * anyway, your work is great! now i can write my own script with it.
> 
> Thanks for your feedback! I am glad to see people other than myself have a use for it!
> 
> I would like to point out that the license can't be changed from creative commons as I am required to use the same license as the original Crowbar program used, as ShareAlike is a part of the creative commons license.
> 
> > ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original
> 
> I didn't think to look/add a .gitignore at the time of making this program, so I will go ahead and add that now. Might lessen the repository size a bit.
> 
> Anyways, thanks for your input. Have a nice evening! Feel free to respond with any more suggestions/questions!

evening? well, it is 10:50 AM in Beijing time ,XD.

**Comment by UltraTechX** [comment]
> > > * creative commons license is not very suit for a program. https://choosealicense.com/non-software/
> > > * why not add a .gitignore file like [this one](https://github.com/gordonwalkedby/WLib2/blob/master/.gitignore).
> > > * anyway, your work is great! now i can write my own script with it.
> > 
> > 
> > Thanks for your feedback! I am glad to see people other than myself have a use for it!
> > I would like to point out that the license can't be changed from creative commons as I am required to use the same license as the original Crowbar program used, as ShareAlike is a part of the creative commons license.
> > > ShareAlike — If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original
> > 
> > 
> > I didn't think to look/add a .gitignore at the time of making this program, so I will go ahead and add that now. Might lessen the repository size a bit.
> > Anyways, thanks for your input. Have a nice evening! Feel free to respond with any more suggestions/questions!
> 
> evening? well, it is 10:50 AM in Beijing time ,XD.

Ah, I see. It's currently 10:55 PM in U.S. Eastern Time.
